// GENERATED by tools/bake-geodata.py -- edit the calibration there, not here.
// shoreNormalDeg / shoreDistM / fetchKm are derived from OSM coastline geometry;
// everything else is hand calibration that the regional models cannot resolve.

export const SITES = [
  {
    id: "kubu", name: "Kubu / Boga Wreck", area: "Kubu",
    lat: -8.2496, lon: 115.5806, entry: "shore",
    depthM: 22, bedDepthM: 18, maxVis: 26,
    sediment: 1.0, currentSensitivity: 0.8, runoff: 0.35,
    shoreNormalDeg: 55, shoreDistM: 440,
    fetchKm: [40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,12.4,3.8,1.4,0.8,0.6,0.5,0.5,0.5,0.4,0.4,0.5,0.5,0.5,0.6,0.8,1.1,1.6,40.0,40.0,40.0,40.0,40.0],
    desc: "A deeper wreck on a sloping volcanic shore. The bed is far enough down that only longer-period swell reaches it."
  },
  {
    id: "liberty", name: "USAT Liberty", area: "Tulamben",
    lat: -8.2744, lon: 115.5932, entry: "shore",
    depthM: 18, bedDepthM: 12, maxVis: 25,
    sediment: 1.25, currentSensitivity: 0.65, runoff: 0.55,
    shoreNormalDeg: 60, shoreDistM: 95,
    fetchKm: [40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,12.5,0.6,0.6,0.4,0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.2,0.2,0.3,0.7,40.0,40.0],
    desc: "Shallow wreck on a black-sand shore entry. Fine volcanic sediment sits right on the wreck and is stirred by both swell and divers."
  },
  {
    id: "coral", name: "Coral Garden", area: "Tulamben",
    lat: -8.2765, lon: 115.5949, entry: "shore",
    depthM: 12, bedDepthM: 8, maxVis: 27,
    sediment: 0.85, currentSensitivity: 0.55, runoff: 0.35,
    shoreNormalDeg: 48, shoreDistM: 116,
    fetchKm: [40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,0.5,0.3,0.3,0.3,0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.2,0.2,0.3,0.4,0.6,40.0,40.0,40.0],
    desc: "Shallow reef on mixed volcanic substrate with more cobble and less fine sand than the Liberty, so it clears faster after swell."
  },
  {
    id: "dropoff", name: "Tulamben Drop-Off", area: "Tulamben",
    lat: -8.2778, lon: 115.5965, entry: "shore",
    depthM: 25, bedDepthM: 10, maxVis: 30,
    sediment: 0.7, currentSensitivity: 1.05, runoff: 0.45,
    shoreNormalDeg: 19, shoreDistM: 110,
    fetchKm: [40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,0.3,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.3,0.4,0.6,1.0,40.0,40.0,40.0],
    desc: "Steep wall running into blue water. Clearer offshore water reaches it first, but alongshore flow can build quickly and unpredictably."
  },
  {
    id: "batu", name: "Batu Kelebit", area: "Tulamben",
    lat: -8.2838, lon: 115.6027, entry: "boat",
    depthM: 20, bedDepthM: 16, maxVis: 31,
    sediment: 0.75, currentSensitivity: 1.15, runoff: 0.25,
    shoreNormalDeg: 46, shoreDistM: 41,
    fetchKm: [40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.1,40.0,40.0,40.0],
    desc: "Offshore reef reached by boat. Usually the clearest water in the area, with correspondingly more exposure to regional current."
  },
  {
    id: "seraya", name: "Seraya Secrets", area: "Seraya",
    lat: -8.2901, lon: 115.6091, entry: "shore",
    depthM: 14, bedDepthM: 10, maxVis: 18,
    sediment: 1.35, currentSensitivity: 0.7, runoff: 0.65,
    shoreNormalDeg: 47, shoreDistM: 205,
    fetchKm: [40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,9.4,1.3,0.7,0.5,0.3,0.3,0.3,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.3,0.3,0.4,0.5,0.6,0.8,40.0,40.0,40.0],
    desc: "Muck site over very fine black sand. Baseline visibility is deliberately low and it is the most sediment-sensitive site on this coast."
  },
  {
    id: "jemeluk", name: "Jemeluk Bay", area: "Amed",
    lat: -8.337, lon: 115.6603, entry: "shore",
    depthM: 14, bedDepthM: 10, maxVis: 28,
    sediment: 0.8, currentSensitivity: 0.55, runoff: 0.5,
    shoreNormalDeg: 22, shoreDistM: 155,
    fetchKm: [40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,0.3,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.3,5.9,40.0,40.0,40.0,40.0],
    desc: "Sheltered bay reef inside a headland. Local runoff and diver traffic usually matter more than anything happening offshore."
  },
  {
    id: "pyramid", name: "Amed Pyramids", area: "Amed",
    lat: -8.3342, lon: 115.6538, entry: "shore",
    depthM: 15, bedDepthM: 12, maxVis: 27,
    sediment: 0.85, currentSensitivity: 0.9, runoff: 0.4,
    shoreNormalDeg: 356, shoreDistM: 39,
    fetchKm: [40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,0.1,0.1,0.1,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.1,0.2,0.4,1.0,1.6,2.2,3.4,4.9,40.0,40.0,40.0,40.0],
    desc: "Artificial reef structures on open sand, exposed to variable alongshore current sweeping around the Amed headland."
  },
];

export const SITE_BY_ID = new Map(SITES.map(s => [s.id, s]));
